"""empty message

Revision ID: 0b3e59872332
Revises: ee94e8574d83
Create Date: 2016-10-25 09:21:10.681609

"""

# revision identifiers, used by Alembic.
revision = '0b3e59872332'
down_revision = 'ee94e8574d83'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buttons', sa.Column('time_last', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buttons', 'time_last')
    ### end Alembic commands ###
