"""empty message

Revision ID: 2af447c66162
Revises: 72839c3cf704
Create Date: 2016-10-24 14:17:53.995376

"""

# revision identifiers, used by Alembic.
revision = '2af447c66162'
down_revision = '72839c3cf704'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buttons', sa.Column('time_loop', sa.Float(), nullable=True))
    op.drop_column('buttons', 'time_refresh')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buttons', sa.Column('time_refresh', mysql.FLOAT(), nullable=True))
    op.drop_column('buttons', 'time_loop')
    ### end Alembic commands ###
