"""empty message

Revision ID: 72839c3cf704
Revises: a3a7d7634134
Create Date: 2016-10-24 14:11:27.034840

"""

# revision identifiers, used by Alembic.
revision = '72839c3cf704'
down_revision = 'a3a7d7634134'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buttons', sa.Column('time_refresh', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buttons', 'time_refresh')
    ### end Alembic commands ###
