"""empty message

Revision ID: 78a77303ef70
Revises: 0b3e59872332
Create Date: 2016-11-02 10:20:51.049668

"""

# revision identifiers, used by Alembic.
revision = '78a77303ef70'
down_revision = '0b3e59872332'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buttons', sa.Column('time_close', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buttons', 'time_close')
    ### end Alembic commands ###
