"""empty message

Revision ID: 7e51a6af2ed3
Revises: None
Create Date: 2016-10-21 11:38:40.450126

"""

# revision identifiers, used by Alembic.
revision = '7e51a6af2ed3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buttons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('time_init', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_press', sa.Float(), nullable=True),
    sa.Column('button_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['button_id'], ['buttons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('times')
    op.drop_table('buttons')
    ### end Alembic commands ###
