"""empty message

Revision ID: 999eca56d55a
Revises: 7e51a6af2ed3
Create Date: 2016-10-21 11:45:21.195318

"""

# revision identifiers, used by Alembic.
revision = '999eca56d55a'
down_revision = '7e51a6af2ed3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buttons', sa.Column('first_name', sa.String(length=64), nullable=True))
    op.drop_index('name', table_name='buttons')
    op.create_unique_constraint(None, 'buttons', ['first_name'])
    op.drop_column('buttons', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buttons', sa.Column('name', mysql.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'buttons', type_='unique')
    op.create_index('name', 'buttons', ['name'], unique=True)
    op.drop_column('buttons', 'first_name')
    ### end Alembic commands ###
