"""empty message

Revision ID: 9c4c2999bc2f
Revises: None
Create Date: 2016-11-08 10:37:30.229790

"""

# revision identifiers, used by Alembic.
revision = '9c4c2999bc2f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('time_loop', sa.Float(), nullable=True),
    sa.Column('time_init', sa.String(length=64), nullable=True),
    sa.Column('time_last', sa.String(length=64), nullable=True),
    sa.Column('time_close', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_complete', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('times')
    op.drop_table('tasks')
    ### end Alembic commands ###
