"""empty message

Revision ID: 9ebd90e44f68
Revises: 2af447c66162
Create Date: 2016-10-24 14:53:37.695531

"""

# revision identifiers, used by Alembic.
revision = '9ebd90e44f68'
down_revision = '2af447c66162'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buttons', 'time_init')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buttons', sa.Column('time_init', mysql.FLOAT(), nullable=True))
    ### end Alembic commands ###
