"""empty message

Revision ID: a3a7d7634134
Revises: 999eca56d55a
Create Date: 2016-10-21 11:46:03.066799

"""

# revision identifiers, used by Alembic.
revision = 'a3a7d7634134'
down_revision = '999eca56d55a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buttons', sa.Column('name', sa.String(length=64), nullable=True))
    op.drop_index('first_name', table_name='buttons')
    op.create_unique_constraint(None, 'buttons', ['name'])
    op.drop_column('buttons', 'first_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buttons', sa.Column('first_name', mysql.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'buttons', type_='unique')
    op.create_index('first_name', 'buttons', ['first_name'], unique=True)
    op.drop_column('buttons', 'name')
    ### end Alembic commands ###
