"""empty message

Revision ID: ee94e8574d83
Revises: c8c6fe8aacf8
Create Date: 2016-10-24 15:00:12.164249

"""

# revision identifiers, used by Alembic.
revision = 'ee94e8574d83'
down_revision = 'c8c6fe8aacf8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('times', sa.Column('time_press', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('times', 'time_press')
    ### end Alembic commands ###
